# Generated by Django 6.0.5 on 2026-06-02 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='profile')),
                ('short_bio', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('discord', models.URLField(blank=True)),
                ('bale', models.URLField(blank=True)),
                ('resume', models.FileField(upload_to='resumes')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_domain', models.URLField()),
                ('logo', models.ImageField(upload_to='sitesets')),
                ('favicon', models.ImageField(upload_to='sitesets')),
                ('copyright_text', models.TextField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('priority', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
