# Generated by Django 6.0.5 on 2026-06-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_favicon_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
