# Generated by Django 6.0.5 on 2026-06-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_slug_alter_post_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategory',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='blogCategory',
        ),
    ]
